// Response Contract - AGENTS.md Section 8
// Every response object generated by the AI engine must include these fields

export interface ResponseContract {
  message: string; // required
  options?: string[] | null; // array of quick replies - optional, null if not applicable
  next_action: string; // required (show_catalogue | open_subscription | escalate | end_session | ...)
  intent_detected: string; // required, logged to Interaction Log
  escalate: boolean;
  language: 'en-NG' | 'pcm-NG'; // default: en-NG (Standard Nigerian English)
}

// Valid next_action values based on AGENTS.md Section 7 (Intent → Action Mapping)
export const VALID_NEXT_ACTIONS = [
  'show_catalogue',
  'open_subscription',
  'escalate',
  'end_session',
  'start_onboarding',
  'show_events',
  'volunteer_signup',
  'support',
  'redirect_scope'
] as const;

// Language rule: match the language the user writes in
// Default to en-NG (Standard Nigerian English)
// Support pcm-NG (Nigerian Pidgin)
// Never switch language mid-session without the user initiating it
export function detectLanguage(message: string): 'en-NG' | 'pcm-NG' {
  // Simple Pidgin detection (can be enhanced with ML model)
  const pidginMarkers = ['how far', 'how u dey', 'wetin', 'dey', 'no be', 'abeg', 'oya', 'na so'];
  const lowerMessage = message.toLowerCase();
  
  for (const marker of pidginMarkers) {
    if (lowerMessage.includes(marker)) {
      return 'pcm-NG';
    }
  }
  
  return 'en-NG';
}

// Validate response contract
export function validateResponse(response: any): response is ResponseContract {
  return (
    typeof response.message === 'string' &&
    typeof response.next_action === 'string' &&
    typeof response.intent_detected === 'string' &&
    typeof response.escalate === 'boolean' &&
    (response.language === 'en-NG' || response.language === 'pcm-NG')
  );
}
